data_upload:
  root_dir: artifacts/raw_data
  source_URL: https://drive.google.com/file/d/19nyK54FijEPS4Vq9QHzJfpjpbQDhd_Y6/view?usp=sharing
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts
  data_path: artifacts/Train.csv

data_ingest:
  feature_store : "artifacts/data_ingestion/feature_store/data.csv"
  TRAIN_TEST_SPLIT_RATIO: 0.25
  FILE_NAME : "artifacts/data_ingestion/feature_store/data.csv"
  TRAIN_FILE_NAME: "artifacts/data_ingestion/ingested/train.csv"
  TEST_FILE_NAME: "artifacts/data_ingestion/ingested/test.csv"
  TRAIN_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_train.csv
  TEST_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_test.csv  

model_training :
  TRAIN_FILE_NAME: "artifacts/data_ingestion/ingested/train.csv"
  TEST_FILE_NAME: "artifacts/data_ingestion/ingested/test.csv"
  TRAIN_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_train.csv
  TEST_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_test.csv  
  model: "app/model.pkl"

processed_data_path: "artifacts/processed_data.csv"

# For MongoDB connection
DATABASE_NAME : "Churn_rate" 
COLLECTION_NAME : "Churn_Data"
MONGODB_URL_KEY : "MONGODB_URL"