data_upload:
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts
  nflx_csv_path : artifacts/NFLX.csv

data_ingest:
  s3_data : "uploaded_data/NFLX.csv"
  feature_store : "artifacts/data_ingestion/feature_store/NFLX.csv"
  TRAIN_FILE_NAME: "artifacts/data_ingestion/ingested/train.csv"
  TEST_FILE_NAME: "artifacts/data_ingestion/ingested/test.csv"
  TRAIN_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_train.csv
  TEST_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_test.csv  
  processed_data_path: "artifacts/data_ingestion/processed_data/processed_data.csv"

model_training :
  TRAIN_FILE_NAME: "artifacts/data_ingestion/ingested/train.csv"
  TEST_FILE_NAME: "artifacts/data_ingestion/ingested/test.csv"
  TRAIN_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_train.csv
  TEST_LABEL_FILE_NAME: artifacts/data_ingestion/ingested/y_test.csv  
  model: "app/model.pkl"


