apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fastapi-serve
spec:
  predictor:
    containers:
      - name: fastapi-container
        image: 684931265998.dkr.ecr.eu-north-1.amazonaws.com/fastapi-inference:latest-v1
        command: ["uvicorn"]
        args: ["app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
          - name: AWS_DEFAULT_REGION
            value: "eu-north-1"
          - name: S3_BUCKET_NAME
            value: "learnyard-data-ingestion"
          - name: MODEL_S3_KEY
            value: "models/model.pkl"
        ports:
          - containerPort: 8000
