apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda
  template:
    metadata:
      labels:
        app: lambda
    spec:
      containers:
        - name: lambda-container
          image: 684931265998.dkr.ecr.us-east-1.amazonaws.com/lambda:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: lambda-service
spec:
  selector:
    app: lambda
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
