apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fastapi-serve
spec:
  predictor:
    containers:
    - name: kserve-container
      image: <your-ecr-url>/fastapi-inference
      ports:
        - containerPort: 8080
